In [26]:
import numpy as np
def array_manipulation():
    size = int(input("Enter the size of the array: "))
    array = np.random.randint(1, 10, size)
    print("\nOriginal Array:")
    print(array)
    # Square and Cube each element in the array
    squared_array = np.square(array)
    print("\nSquared Array:")
    print(squared_array)
    cubed_array = np.power(array,3)
    print("\nCubed Array:")
    print(cubed_array)
print("Array Manipulation Example")
array_manipulation()

Array Manipulation Example
Enter the size of the array: 6

Original Array:
[4 5 6 9 2 2]

Squared Array:
[16 25 36 81  4  4]

Cubed Array:
[ 64 125 216 729   8   8]


In [25]:
import numpy as np
def numerical_operations():
    data = np.random.randint(1, 100, 10)
    print("\nGenerated Data:")
    print(data)
    # Calculate mean and standard deviation
    mean_value = np.mean(data)
    std_dev = np.std(data)
    print("\nMean:", mean_value)
    print("Standard Deviation:", std_dev)
print("Numerical Operations Example")
numerical_operations()

Numerical Operations Example

Generated Data:
[34 57 34 20 16 75 72 28 72 77]

Mean: 48.5
Standard Deviation: 23.23897588104949


In [24]:
import numpy as np
def linear_algebra_operations():
    size = int(input("Enter the size of the square matrix: "))
    matrix = np.random.randint(1, 10, (size, size))
    print("\nGenerated Matrix:")
    print(matrix)
    # Calculate determinant and inverse of the matrix
    det = np.linalg.det(matrix)
    inverse_matrix = np.linalg.inv(matrix)
    print("\nDeterminant:", det)
    print("Inverse Matrix:")
    print(inverse_matrix)
print("Linear Algebra Operations Example")
linear_algebra_operations()

Linear Algebra Operations Example
Enter the size of the square matrix: 5

Generated Matrix:
[[2 5 1 1 7]
 [8 9 8 5 1]
 [8 4 5 5 1]
 [1 6 1 5 7]
 [6 5 6 5 6]]

Determinant: 3976.999999999997
Inverse Matrix:
[[ 0.17852653 -0.08599447  0.27382449 -0.09630375 -0.12723158]
 [ 0.08674881  0.14131255 -0.02891627  0.05883832 -0.18858436]
 [-0.14458134  0.09781242 -0.28513955 -0.09806387  0.31430727]
 [-0.22705557 -0.05682675  0.07568519  0.21121448  0.01533819]
 [ 0.08297712 -0.08222278 -0.02765904 -0.03067639  0.12396279]]
